.TH "eet.c" 3 "1 Apr 2008" "Eet" \" -*- nroff -*-
.ad l
.nh
.SH NAME
eet.c \- 
.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
Eet Data Handling Library Public API CallsThese routines are used for Eet Library interaction 
.SH "Author"
.PP 
Generated automatically by Doxygen for Eet from the source code.
