.TH "eet.c" 3 "19 May 2008" "Eet" \" -*- nroff -*-
.ad l
.nh
.SH NAME
eet.c \- Eet Data Handling Library Public API Calls. 
.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
Eet Data Handling Library Public API Calls. 

These routines are used for Eet Library interaction 
.SH "Author"
.PP 
Generated automatically by Doxygen for Eet from the source code.
